colisiones
PLeon08/ProyectoED pull request #19
Opened 2020-10-15 22:12 UTC by nallelygonzalez16

2020-10-15 22:17 UTC, MariluzSC commented
Gracias

2020-10-15 22:19 UTC, PLeon08 approved these changes

2020-10-15 22:32 UTC, MariluzSC approved these changes

2020-10-15 22:38 UTC, MariluzSC approved these changes

2020-10-15 22:39 UTC, PLeon08 requested changes
Intentando reparar el archivo @nallelygonzalez16 nos rompió el archivo

2020-10-15 22:39 UTC, MariluzSC approved these changes
Aceptando los cambios

2020-10-15 22:43 UTC, PLeon08 approved these changes
Arreglar

2020-10-15 22:43 UTC, PLeon08 commented
Recibiendo archivo

> Intentando reparar el archivo

2020-10-15 22:51 UTC, MariluzSC approved these changes

2020-10-16 06:01 UTC, nallelygonzalez16 commented
no sirvió

2020-10-16 06:01 UTC, closed without merging